In [1]:
# Import the libraries

import numpy as np

In [2]:
# Create a list

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [3]:
# Convert list to Numpy Array
# Every element is the same type

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [4]:
# Show the numpy array dimensions

A.ndim

2

In [5]:
# Show the numpy array shape

A.shape

(3, 3)

In [6]:
# Show the numpy array size

A.size

9

In [7]:
# Access the element on the second row and third column

A[1, 2]

23

In [8]:
# Access the element on the second row and third column

A[1][2]

23

In [9]:
# Access the element on the first row and first column

A[0][0]

11

In [10]:
# Access the element on the first row and first and second columns

A[0][0:2]

array([11, 12])

In [11]:
# Access the element on the first and second rows and third column

A[0:2, 2]

array([13, 23])

In [12]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [13]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [14]:
# Add X and Y

Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [15]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [16]:
# Multiply Y with 2

Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

In [17]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [18]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [19]:
# Multiply X with Y

Z = X * Y
Z

array([[2, 0],
       [0, 2]])

In [20]:
# Create a matrix A

A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [21]:
# Create a matrix B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [22]:
# Calculate the dot product

Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [23]:
# Calculate the sine of Z

np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [24]:
# Create a matrix C

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [25]:
# Get the transposed of C

C.T

array([[1, 2, 3],
       [1, 2, 3]])

In [26]:
# Write your code below and press Shift+Enter to execute

a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
A = np.array(a)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
# Write your code below and press Shift+Enter to execute
A.size

12

In [28]:
# Write your code below and press Shift+Enter to execute
A[0][0:2]

array([1, 2])

In [29]:
# Write your code below and press Shift+Enter to execute

B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])
X = np.dot(A,B)
X

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])